### ISSUE TITLE
python-novaclient-2.6.6 package cannot be downloaded

### ISSUE THREAD

**Issue by frostyplanet** [TMG-nl/openstack-overlay#4]
> > > Downloading 'http://pypi.python.org/packages/source/p/python-novaclient/python-novaclient-2.6.6.tar.gz'
> > > --2012-02-19 16:19:44--  http://pypi.python.org/packages/source/p/python-novaclient/python-novaclient-2.6.6.tar.gz
> > > Resolving pypi.python.org... 82.94.164.168, 2001:888:2000:d::a8
> > > Connecting to pypi.python.org|82.94.164.168|:80... connected.
> > > HTTP request sent, awaiting response... 404 Not Found
> > > 2012-02-19 16:19:44 ERROR 404: Not Found.

---

it seams pypi no longer provide that version of package, I have to rename python-novaclient-2.6.6.ebuild into python-novaclient-2012.1.ebuild to install

**Comment by CorCornelisse** [comment]
Thanks for noticing, it's fixed with this commit:

d8026e77498a4eb51b57713a906f3642a2e88311
